repos:
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.0.1
    hooks:
      - id: doctoc
        exclude: ^vendor/
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
        exclude: ^vendor/
      - id: go-imports
        exclude: ^vendor/
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: insert-license
        exclude: ^vendor/
        files: \.go$
        args:
          - --license-filepath
          - LICENSE
          - --comment-style
          - /*| *| */